import { createHash } from "node:crypto";

export const M0_03_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/database/m0-03-policy-contract.md",
    "contracts/policy/core-policy-v1.json",
    "contracts/schemas/core-policy-manifest.schema.json",
    "contracts/schemas/examples/core-policy-manifest.invalid.json",
    "contracts/schemas/examples/core-policy-manifest.valid.json",
    "contracts/schemas/examples/policy-decision.invalid.json",
    "contracts/schemas/examples/policy-decision.valid.json",
    "contracts/schemas/examples/policy-evaluation.invalid.json",
    "contracts/schemas/examples/policy-evaluation.valid.json",
    "contracts/schemas/policy-decision.schema.json",
    "contracts/schemas/policy-evaluation.schema.json",
    "contracts/schemas/semantic-fixtures/policy-decision-allow-reason.invalid.json",
    "contracts/schemas/semantic-fixtures/policy-decision-human-recorder.invalid.json",
    "contracts/schemas/semantic-fixtures/policy-evaluation-gate-assignment.invalid.json",
    "contracts/schemas/semantic-fixtures/policy-evaluation-gate-assignment.valid.json",
    "contracts/schemas/semantic-fixtures/policy-evaluation-human-service-auth.invalid.json",
    "contracts/schemas/semantic-fixtures/policy-evaluation-human-service-role.invalid.json",
    "contracts/schemas/semantic-fixtures/policy-evaluation-service-human-role.invalid.json",
    "contracts/schemas/semantic-fixtures/policy-evaluation-service-membership.invalid.json",
    "contracts/schemas/semantic-fixtures/policy-evaluation-service-version.invalid.json",
    "contracts/schemas/semantic-fixtures/policy-evaluation-service.valid.json",
    "contracts/schemas/semantic-fixtures/policy-evaluation-target-version.invalid.json",
    "contracts/schemas/semantic-fixtures/policy-evaluation-target-version.valid.json",
    "contracts/schemas/semantic-fixtures/policy-evaluation-transition-service.valid.json",
    "docs/curve-ai-native-sdlc-prd.md",
    "docs/technical/architecture.md",
    "docs/technical/domain-model.md",
    "docs/technical/m0-03-core-policy-task-packet.md",
    "docs/technical/m0-authorization-and-state-matrices.md",
    "docs/technical/m0-s2-implementation-evidence.md",
    "docs/technical/security-and-operations.md",
    "scripts/lib/context-pack.mjs",
    "scripts/validate-contracts.mjs",
  ].sort(),
);

export const M0_S3_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/database/m0-03-policy-contract.md",
    "contracts/database/m0-s2-relational-contract.md",
    "contracts/policy/core-policy-v1.json",
    "contracts/schemas/audit-event.schema.json",
    "contracts/schemas/common.schema.json",
    "contracts/schemas/event-envelope.schema.json",
    "contracts/schemas/idempotency-record.schema.json",
    "contracts/schemas/inbox-message.schema.json",
    "contracts/schemas/operation-event-v1.schema.json",
    "contracts/schemas/operation.schema.json",
    "contracts/schemas/operation-summary.schema.json",
    "contracts/schemas/outbox-event.schema.json",
    "contracts/schemas/policy-decision.schema.json",
    "contracts/schemas/policy-evaluation.schema.json",
    "contracts/schemas/semantic-fixtures/idempotency-completed.valid.json",
    "contracts/schemas/semantic-fixtures/idempotency-raw-key.invalid.json",
    "contracts/schemas/semantic-fixtures/idempotency-terminal-null.invalid.json",
    "contracts/schemas/semantic-fixtures/inbox-processed-null.invalid.json",
    "contracts/schemas/semantic-fixtures/operation-terminal-null.invalid.json",
    "contracts/schemas/semantic-fixtures/operation-terminal.valid.json",
    "contracts/schemas/semantic-fixtures/outbox-claim-null.invalid.json",
    "contracts/schemas/semantic-fixtures/outbox-claim.valid.json",
    "contracts/schemas/semantic-fixtures/outbox-delivery-null.invalid.json",
    "contracts/schemas/semantic-fixtures/outbox-delivery.valid.json",
    "contracts/schemas/semantic-fixtures/outbox-retry-null.invalid.json",
    "contracts/schemas/semantic-fixtures/outbox-retry.valid.json",
    "contracts/schemas/semantic-fixtures/policy-evaluation-transition-service.valid.json",
    "contracts/temporal/m0-workflow-contract.md",
    "docs/curve-ai-native-sdlc-prd.md",
    "docs/technical/adr-003-runtime-topology.md",
    "docs/technical/architecture.md",
    "docs/technical/d003-local-topology-decision-packet.md",
    "docs/technical/d003-private-platform-connectivity-amendment.md",
    "docs/technical/m0-03-implementation-evidence.md",
    "docs/technical/m0-authorization-and-state-matrices.md",
    "docs/technical/m0-local-skeleton-task-packets.md",
    "docs/technical/m0-s2-implementation-evidence.md",
    "docs/technical/security-and-operations.md",
    "scripts/lib/context-pack.mjs",
    "scripts/validate-contracts.mjs",
  ].sort(),
);

export const M0_08_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/observability/obs-bind-001-local-v1.json",
    "contracts/observability/m0-s5-telemetry-v1.json",
    "contracts/openapi/curve-v1.openapi.yaml",
    "contracts/schemas/common.schema.json",
    "contracts/schemas/event-envelope.schema.json",
    "contracts/schemas/examples/operation-event-v1.invalid.json",
    "contracts/schemas/examples/operation-event-v1.valid.json",
    "contracts/schemas/examples/operation-event-v2.invalid.json",
    "contracts/schemas/examples/operation-event-v2.valid.json",
    "contracts/schemas/examples/telemetry-manifest.invalid.json",
    "contracts/schemas/examples/telemetry-manifest.valid.json",
    "contracts/schemas/operation-event-v1.schema.json",
    "contracts/schemas/operation-event-v2.schema.json",
    "contracts/schemas/observability-binding.schema.json",
    "contracts/schemas/operation-summary.schema.json",
    "contracts/schemas/operation.schema.json",
    "contracts/schemas/semantic-fixtures/operation-event-v2-tracestate.invalid.json",
    "contracts/schemas/semantic-fixtures/observability-binding-external-delivery.invalid.json",
    "contracts/schemas/sse-event.schema.json",
    "contracts/schemas/telemetry-manifest.schema.json",
    "contracts/temporal/m0-workflow-contract.md",
    "docs/curve-ai-native-sdlc-prd.md",
    "docs/technical/architecture.md",
    "docs/technical/domain-model.md",
    "docs/technical/m0-authorization-and-state-matrices.md",
    "docs/technical/m0-local-skeleton-task-packets.md",
    "docs/technical/m0-readiness-board.md",
    "docs/technical/m0-s4-implementation-evidence.md",
    "docs/technical/m0-s5-observability-task-packet.md",
    "docs/technical/m0-s5a-implementation-evidence.md",
    "docs/technical/m0-s5b-implementation-evidence.md",
    "docs/technical/m0-traceability.md",
    "docs/technical/obs-bind-001-local-observability-binding.md",
    "docs/technical/security-and-operations.md",
    "docs/technical/ux-m0-s4-foundation-probe.md",
    "scripts/lib/context-pack.mjs",
    "scripts/validate-contracts.mjs",
  ].sort(),
);


export const M0_S4_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/openapi/curve-v1.openapi.yaml",
    "contracts/policy/core-policy-v1.json",
    "contracts/schemas/common.schema.json",
    "contracts/schemas/event-envelope.schema.json",
    "contracts/schemas/examples/event-envelope.invalid.json",
    "contracts/schemas/examples/event-envelope.valid.json",
    "contracts/schemas/examples/operation-event-v1.invalid.json",
    "contracts/schemas/examples/operation-event-v1.valid.json",
    "contracts/schemas/examples/operation.invalid.json",
    "contracts/schemas/examples/operation.valid.json",
    "contracts/schemas/operation-event-v1.schema.json",
    "contracts/schemas/operation-summary.schema.json",
    "contracts/schemas/operation.schema.json",
    "contracts/schemas/semantic-fixtures/idempotency-completed.valid.json",
    "contracts/schemas/semantic-fixtures/idempotency-raw-key.invalid.json",
    "contracts/schemas/semantic-fixtures/idempotency-terminal-null.invalid.json",
    "contracts/schemas/semantic-fixtures/operation-terminal-null.invalid.json",
    "contracts/schemas/semantic-fixtures/operation-terminal.valid.json",
    "contracts/schemas/sse-event.schema.json",
    "contracts/temporal/m0-workflow-contract.md",
    "docs/curve-ai-native-sdlc-prd.md",
    "docs/design/curve-brand.md",
    "docs/design/mockups/curve-foundation-probe-v2.png",
    "docs/design/prototypes/m0-s4-foundation-probe/curve-logo-light-ui-v1.webp",
    "docs/design/prototypes/m0-s4-foundation-probe/index.html",
    "docs/technical/adr-003-runtime-topology.md",
    "docs/technical/architecture.md",
    "docs/technical/curve-experience-blueprint.md",
    "docs/technical/development-plan.md",
    "docs/technical/integration-contracts.md",
    "docs/technical/m0-authorization-and-state-matrices.md",
    "docs/technical/m0-local-skeleton-task-packets.md",
    "docs/technical/m0-readiness-board.md",
    "docs/technical/m0-s3-implementation-evidence.md",
    "docs/technical/security-and-operations.md",
    "docs/technical/ux-m0-s4-foundation-probe.md",
    "scripts/lib/context-pack.mjs",
    "scripts/validate-contracts.mjs",
  ].sort(),
);

export const M0_S6A_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/observability/m0-s5-telemetry-v1.json",
    "contracts/schemas/examples/temporal-orchestration.invalid.json",
    "contracts/schemas/examples/test-strategy-matrix.invalid.json",
    "contracts/schemas/telemetry-manifest.schema.json",
    "contracts/schemas/temporal-orchestration.schema.json",
    "contracts/schemas/test-strategy-matrix.schema.json",
    "contracts/testing/ac-test-matrix-v1.json",
    "contracts/temporal/m0-orchestration-v1.json",
    "contracts/temporal/m0-workflow-contract.md",
    "docs/curve-ai-native-sdlc-prd.md",
    "docs/technical/adr-003-runtime-topology.md",
    "docs/technical/architecture.md",
    "docs/technical/development-plan.md",
    "docs/technical/m0-s3-implementation-evidence.md",
    "docs/technical/m0-s5b-implementation-evidence.md",
    "docs/technical/m0-s6a-durable-orchestration-task-packet.md",
    "docs/technical/m0-test-strategy.md",
    "docs/technical/m0-traceability.md",
    "docs/technical/security-and-operations.md",
    "docs/technical/workflows-and-sequences.md",
    "scripts/lib/context-pack.mjs",
    "scripts/lib/temporal-orchestration.mjs",
    "scripts/lib/test-strategy.mjs",
    "scripts/tests/temporal-orchestration.test.mjs",
    "scripts/tests/test-strategy.test.mjs",
    "scripts/validate-contracts.mjs",
  ].sort(),
);

export const RUNTIME_M0_01_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/README.md",
    "contracts/schemas/coding-agent-context-pack-manifest.schema.json",
    "contracts/schemas/coding-agent-implementation-authorization.schema.json",
    "contracts/schemas/coding-agent-source-catalog.schema.json",
    "contracts/schemas/coding-agent-state-evidence.schema.json",
    "contracts/schemas/coding-agent-task-packet.schema.json",
    "contracts/task-packet-authorizations/README.md",
    "contracts/task-packets/README.md",
    "contracts/testing/ac-test-matrix-v1.json",
    "contracts/temporal/m0-workflow-contract.md",
    "docs/curve-ai-native-sdlc-prd.md",
    "docs/technical/adr-001-plane-upstream-foundation.md",
    "docs/technical/adr-003-runtime-topology.md",
    "docs/technical/architecture.md",
    "docs/technical/architecture-decisions.md",
    "docs/technical/coding-agent-local-execution-decision.md",
    "docs/technical/development-plan.md",
    "docs/technical/local-runtime-refresh-evidence.md",
    "docs/technical/m0-completion-audit.md",
    "docs/technical/m0-readiness-board.md",
    "docs/technical/m0-s6a-durable-orchestration-task-packet.md",
    "docs/technical/m0-s6a-implementation-evidence.md",
    "docs/technical/m0-test-strategy.md",
    "docs/technical/m0-traceability.md",
    "docs/technical/runtime-m0-01-graceful-shutdown-task-packet.md",
    "docs/technical/security-and-operations.md",
    "scripts/lib/coding-agent-task-packet.mjs",
    "scripts/lib/context-pack.mjs",
    "scripts/tests/coding-agent-task-packet.test.mjs",
    "scripts/tests/runtime-m0-01-task-packet.test.mjs",
    "scripts/validate-contracts.mjs",
  ].sort(),
);

export const M0_S9A_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/database/m0-03-policy-contract.md",
    "contracts/database/m0-s2-relational-contract.md",
    "contracts/database/m0-s9a-provider-registry-contract.md",
    "contracts/policy/core-policy-v1.json",
    "contracts/policy/core-policy-v2.json",
    "contracts/providers/m0-s9a-provider-registry-v1.json",
    "contracts/schemas/audit-event.schema.json",
    "contracts/schemas/common.schema.json",
    "contracts/schemas/event-envelope.schema.json",
    "contracts/schemas/examples/provider-capability.invalid.json",
    "contracts/schemas/examples/provider-capability.valid.json",
    "contracts/schemas/examples/provider-connection-event-v1.invalid.json",
    "contracts/schemas/examples/provider-connection-event-v1.valid.json",
    "contracts/schemas/examples/provider-connection.invalid.json",
    "contracts/schemas/examples/provider-connection.valid.json",
    "contracts/schemas/examples/core-policy-manifest-v2.invalid.json",
    "contracts/schemas/examples/core-policy-manifest-v2.valid.json",
    "contracts/schemas/examples/provider-registry-manifest.invalid.json",
    "contracts/schemas/examples/provider-registry-manifest.valid.json",
    "contracts/schemas/examples/provider-reconciliation-event-v1.invalid.json",
    "contracts/schemas/examples/provider-reconciliation-event-v1.valid.json",
    "contracts/schemas/examples/test-strategy-matrix.invalid.json",
    "contracts/schemas/idempotency-record.schema.json",
    "contracts/schemas/inbox-message.schema.json",
    "contracts/schemas/operation.schema.json",
    "contracts/schemas/outbox-event.schema.json",
    "contracts/schemas/policy-decision.schema.json",
    "contracts/schemas/core-policy-manifest-v2.schema.json",
    "contracts/schemas/provider-capability.schema.json",
    "contracts/schemas/provider-connection-event-v1.schema.json",
    "contracts/schemas/provider-connection.schema.json",
    "contracts/schemas/provider-registry-manifest.schema.json",
    "contracts/schemas/provider-reconciliation-event-v1.schema.json",
    "contracts/schemas/test-strategy-matrix.schema.json",
    "contracts/schemas/semantic-fixtures/provider-connection-active-null.invalid.json",
    "contracts/schemas/semantic-fixtures/provider-connection-active.valid.json",
    "contracts/schemas/semantic-fixtures/provider-connection-event-registered.valid.json",
    "contracts/schemas/semantic-fixtures/provider-connection-revoked-next.invalid.json",
    "contracts/schemas/semantic-fixtures/policy-decision-provider-registration-v2.valid.json",
    "contracts/schemas/semantic-fixtures/policy-decision-provider-registration-v3.invalid.json",
    "contracts/testing/ac-test-matrix-v1.json",
    "docs/curve-ai-native-sdlc-prd.md",
    "docs/technical/adr-007-mcp-trust-and-orca-profile.md",
    "docs/technical/architecture-decisions.md",
    "docs/technical/architecture.md",
    "docs/technical/development-plan.md",
    "docs/technical/domain-model.md",
    "docs/technical/integration-contracts.md",
    "docs/technical/m0-03-implementation-evidence.md",
    "docs/technical/m0-authorization-and-state-matrices.md",
    "docs/technical/m0-readiness-board.md",
    "docs/technical/m0-s2-implementation-evidence.md",
    "docs/technical/m0-s4-implementation-evidence.md",
    "docs/technical/m0-s5-observability-task-packet.md",
    "docs/technical/m0-s5a-implementation-evidence.md",
    "docs/technical/m0-s5b-implementation-evidence.md",
    "docs/technical/m0-s9a-registration-authorization-decision.md",
    "docs/technical/m0-s9a-provider-registry-task-packet.md",
    "docs/technical/m0-test-strategy.md",
    "docs/technical/m0-traceability.md",
    "docs/technical/security-and-operations.md",
    "scripts/lib/context-pack.mjs",
    "scripts/lib/test-strategy.mjs",
    "scripts/tests/p0-06-policy.test.mjs",
    "scripts/tests/test-strategy.test.mjs",
    "scripts/validate-contracts.mjs",
  ].sort(),
);

export const M0_S9B_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/database/m0-s2-relational-contract.md",
    "contracts/governance/m0-s9b1-provider-administration-v1.json",
    "contracts/openapi/curve-v1.openapi.yaml",
    "contracts/policy/core-policy-v2.json",
    "contracts/providers/m0-s9a-provider-registry-v1.json",
    "contracts/schemas/audit-event.schema.json",
    "contracts/schemas/common.schema.json",
    "contracts/schemas/event-envelope.schema.json",
    "contracts/schemas/idempotency-record.schema.json",
    "contracts/schemas/inbox-message.schema.json",
    "contracts/schemas/operation.schema.json",
    "contracts/schemas/operation-summary.schema.json",
    "contracts/schemas/outbox-event.schema.json",
    "contracts/schemas/examples/provider-administration-decision.invalid.json",
    "contracts/schemas/examples/provider-connection-administration-page.invalid.json",
    "contracts/schemas/examples/provider-connection-administration-page.valid.json",
    "contracts/schemas/examples/provider-connection-administration.invalid.json",
    "contracts/schemas/examples/provider-connection-administration.valid.json",
    "contracts/schemas/examples/provider-connection-register-request.invalid.json",
    "contracts/schemas/examples/provider-connection-register-request.valid.json",
    "contracts/schemas/provider-administration-decision.schema.json",
    "contracts/schemas/provider-connection-administration-page.schema.json",
    "contracts/schemas/provider-connection-administration.schema.json",
    "contracts/schemas/provider-connection-register-request.schema.json",
    "contracts/schemas/semantic-fixtures/provider-administration-decision-approved.valid.json",
    "contracts/schemas/semantic-fixtures/provider-administration-decision-deferred.valid.json",
    "contracts/schemas/semantic-fixtures/provider-administration-decision-lifecycle.invalid.json",
    "contracts/schemas/provider-capability.schema.json",
    "contracts/schemas/provider-connection-event-v1.schema.json",
    "contracts/schemas/provider-connection.schema.json",
    "contracts/schemas/provider-reconciliation-event-v1.schema.json",
    "contracts/schemas/provider-registry-manifest.schema.json",
    "contracts/testing/ac-test-matrix-v1.json",
    "docs/curve-ai-native-sdlc-prd.md",
    "docs/technical/architecture-decisions.md",
    "docs/technical/architecture.md",
    "docs/technical/development-plan.md",
    "docs/technical/domain-model.md",
    "docs/technical/integration-contracts.md",
    "docs/technical/m0-readiness-board.md",
    "docs/technical/m0-s9a-implementation-evidence.md",
    "docs/technical/m0-s9b-provider-transport-task-packet.md",
    "docs/technical/m0-s9b1-provider-administration-decision.md",
    "docs/technical/m0-test-strategy.md",
    "docs/technical/m0-traceability.md",
    "docs/technical/security-and-operations.md",
    "scripts/lib/context-pack.mjs",
    "scripts/lib/provider-administration-decision.mjs",
    "scripts/tests/m0-s9-remainder-readiness.test.mjs",
    "scripts/tests/provider-administration-decision.test.mjs",
    "scripts/validate-contracts.mjs",
  ].sort(),
);

export const M0_S9B1_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/database/m0-03-policy-contract.md",
    "contracts/database/m0-s2-relational-contract.md",
    "contracts/database/m0-s9a-provider-registry-contract.md",
    "contracts/providers/m0-s9a-provider-registry-v1.json",
    "contracts/schemas/access-envelope.schema.json",
    "contracts/governance/m0-s9b1-provider-administration-v1.json",
    "contracts/openapi/curve-v1.openapi.yaml",
    "contracts/policy/core-policy-v2.json",
    "contracts/schemas/audit-event.schema.json",
    "contracts/schemas/common.schema.json",
    "contracts/schemas/core-policy-manifest-v2.schema.json",
    "contracts/schemas/event-envelope.schema.json",
    "contracts/schemas/examples/provider-administration-decision.invalid.json",
    "contracts/schemas/examples/provider-connection-administration-page.invalid.json",
    "contracts/schemas/examples/provider-connection-administration-page.valid.json",
    "contracts/schemas/examples/provider-connection-administration.invalid.json",
    "contracts/schemas/examples/provider-connection-administration.valid.json",
    "contracts/schemas/idempotency-record.schema.json",
    "contracts/schemas/inbox-message.schema.json",
    "contracts/schemas/operation.schema.json",
    "contracts/schemas/operation-summary.schema.json",
    "contracts/schemas/outbox-event.schema.json",
    "contracts/schemas/policy-decision.schema.json",
    "contracts/schemas/policy-evaluation.schema.json",
    "contracts/schemas/provider-administration-decision.schema.json",
    "contracts/schemas/provider-connection-administration-page.schema.json",
    "contracts/schemas/provider-connection-administration.schema.json",
    "contracts/schemas/examples/provider-connection-register-request.invalid.json",
    "contracts/schemas/examples/provider-connection-register-request.valid.json",
    "contracts/schemas/provider-connection-register-request.schema.json",
    "contracts/schemas/provider-connection-event-v1.schema.json",
    "contracts/schemas/provider-reconciliation-event-v1.schema.json",
    "contracts/schemas/provider-registry-manifest.schema.json",
    "contracts/schemas/semantic-fixtures/provider-administration-decision-approved.valid.json",
    "contracts/schemas/semantic-fixtures/provider-administration-decision-deferred.valid.json",
    "contracts/schemas/semantic-fixtures/provider-administration-decision-lifecycle.invalid.json",
    "contracts/schemas/provider-capability.schema.json",
    "contracts/schemas/provider-connection.schema.json",
    "contracts/testing/ac-test-matrix-v1.json",
    "docs/technical/m0-authorization-and-state-matrices.md",
    "docs/technical/integration-contracts.md",
    "docs/technical/m0-s9a-implementation-evidence.md",
    "docs/technical/m0-s9a-registration-authorization-decision.md",
    "docs/technical/m0-s9b-provider-transport-task-packet.md",
    "docs/technical/m0-s9b1-provider-administration-decision.md",
    "docs/technical/security-and-operations.md",
    "scripts/lib/context-pack.mjs",
    "scripts/lib/provider-administration-decision.mjs",
    "scripts/tests/m0-s9-remainder-readiness.test.mjs",
    "scripts/tests/provider-administration-decision.test.mjs",
    "scripts/validate-contracts.mjs",
  ].sort(),
);

export const M0_S9C_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/policy/core-policy-v2.json",
    "contracts/schemas/audit-event.schema.json",
    "contracts/schemas/event-envelope.schema.json",
    "contracts/schemas/idempotency-record.schema.json",
    "contracts/schemas/operation.schema.json",
    "contracts/schemas/provider-capability.schema.json",
    "contracts/schemas/provider-connection.schema.json",
    "contracts/testing/ac-test-matrix-v2.json",
    "docs/curve-ai-native-sdlc-prd.md",
    "docs/technical/architecture-decisions.md",
    "docs/technical/architecture.md",
    "docs/technical/development-plan.md",
    "docs/technical/domain-model.md",
    "docs/technical/integration-contracts.md",
    "docs/technical/m0-readiness-board.md",
    "docs/technical/m0-s9a-implementation-evidence.md",
    "docs/technical/m0-s9c-model-gateway-task-packet.md",
    "docs/technical/m0-test-strategy.md",
    "docs/technical/m0-traceability.md",
    "docs/technical/security-and-operations.md",
    "scripts/lib/context-pack.mjs",
    "scripts/validate-contracts.mjs",
  ].sort(),
);

export const P0_12_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/README.md",
    "contracts/governance/d009-retention-policy-v1.json",
    "contracts/schemas/examples/retention-policy-decision.invalid.json",
    "contracts/schemas/examples/test-strategy-matrix.invalid.json",
    "contracts/schemas/retention-policy-decision.schema.json",
    "contracts/schemas/test-strategy-matrix.schema.json",
    "contracts/testing/ac-test-matrix-v1.json",
    "docs/curve-ai-native-sdlc-prd.md",
    "docs/technical/adr-009-retention-and-erasure.md",
    "docs/technical/architecture-decisions.md",
    "docs/technical/development-plan.md",
    "docs/technical/m0-readiness-board.md",
    "docs/technical/m0-test-strategy.md",
    "docs/technical/p0-12-retention-decision-task-packet.md",
    "docs/technical/README.md",
    "docs/technical/security-and-operations.md",
    "scripts/lib/context-pack.mjs",
    "scripts/lib/retention-policy.mjs",
    "scripts/lib/test-strategy.mjs",
    "scripts/tests/p0-06-policy.test.mjs",
    "scripts/tests/retention-policy.test.mjs",
    "scripts/tests/test-strategy.test.mjs",
    "scripts/validate-contracts.mjs",
  ].sort(),
);

export const P0_09_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/governance/d002-onyx-delegation-v1.json",
    "contracts/schemas/access-envelope.schema.json",
    "contracts/schemas/examples/onyx-delegation-decision.invalid.json",
    "contracts/schemas/examples/onyx-delegation-decision.valid.json",
    "contracts/schemas/onyx-delegation-decision.schema.json",
    "contracts/schemas/provider-capability.schema.json",
    "contracts/schemas/provider-connection.schema.json",
    "docs/curve-ai-native-sdlc-prd.md",
    "docs/technical/architecture.md",
    "docs/technical/d002-onyx-delegated-identity-decision-packet.md",
    "docs/technical/domain-model.md",
    "docs/technical/m1-alignment-evidence-prd-task-packet.md",
    "docs/technical/m1-m7-task-packets.md",
    "docs/technical/security-and-operations.md",
    "scripts/lib/context-pack.mjs",
    "scripts/lib/onyx-delegation.mjs",
    "scripts/tests/onyx-delegation.test.mjs",
    "scripts/validate-contracts.mjs",
  ].sort(),
);

export const M1_00A_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/database/m1-00a-product-core-relational-contract.md",
    "contracts/governance/m1-00a-product-core-v1.json",
    "contracts/openapi/curve-v1.openapi.yaml",
    "contracts/policy/product-policy-v1.json",
    "contracts/schemas/common.schema.json",
    "contracts/schemas/event-envelope.schema.json",
    "contracts/schemas/examples/product-core-decision.invalid.json",
    "contracts/schemas/examples/product-core-decision.valid.json",
    "contracts/schemas/examples/product-create-request.invalid.json",
    "contracts/schemas/examples/product-create-request.valid.json",
    "contracts/schemas/examples/product-event-v1.invalid.json",
    "contracts/schemas/examples/product-event-v1.valid.json",
    "contracts/schemas/examples/product-policy-manifest.invalid.json",
    "contracts/schemas/examples/product-policy-manifest.valid.json",
    "contracts/schemas/examples/product-reassign-owner-request.invalid.json",
    "contracts/schemas/examples/product-reassign-owner-request.valid.json",
    "contracts/schemas/examples/product-update-request.invalid.json",
    "contracts/schemas/examples/product-update-request.valid.json",
    "contracts/schemas/examples/product.invalid.json",
    "contracts/schemas/examples/product.valid.json",
    "contracts/schemas/product-core-decision.schema.json",
    "contracts/schemas/product-create-request.schema.json",
    "contracts/schemas/product-event-v1.schema.json",
    "contracts/schemas/product-policy-manifest.schema.json",
    "contracts/schemas/product-reassign-owner-request.schema.json",
    "contracts/schemas/product-update-request.schema.json",
    "contracts/schemas/product.schema.json",
    "docs/curve-ai-native-sdlc-prd.md",
    "docs/technical/development-plan.md",
    "docs/technical/domain-model.md",
    "docs/technical/m1-00a-product-core-task-packet.md",
    "docs/technical/m1-alignment-evidence-prd-task-packet.md",
    "scripts/lib/context-pack.mjs",
    "scripts/lib/product-core.mjs",
    "scripts/tests/product-core.test.mjs",
    "scripts/validate-contracts.mjs",
    "scripts/validate-docs.mjs",
  ].sort(),
);

export const M1_01A_CONTEXT_PATHS = Object.freeze(
  [
    "contracts/database/m1-00a-product-core-relational-contract.md",
    "contracts/database/m1-01a-initiative-core-relational-contract.md",
    "contracts/openapi/curve-v1.openapi.yaml",
    "contracts/policy/core-policy-v2.json",
    "contracts/policy/initiative-policy-v1.json",
    "contracts/policy/product-policy-v1.json",
    "contracts/schemas/common.schema.json",
    "contracts/schemas/event-envelope.schema.json",
    "contracts/schemas/examples/gate-assignment.invalid.json",
    "contracts/schemas/examples/gate-assignment.valid.json",
    "contracts/schemas/examples/initiative-create-request.invalid.json",
    "contracts/schemas/examples/initiative-create-request.valid.json",
    "contracts/schemas/examples/initiative-event-v1.invalid.json",
    "contracts/schemas/examples/initiative-event-v1.valid.json",
    "contracts/schemas/examples/initiative-transition-request.invalid.json",
    "contracts/schemas/examples/initiative-transition-request.valid.json",
    "contracts/schemas/examples/initiative-update-request.invalid.json",
    "contracts/schemas/examples/initiative-update-request.valid.json",
    "contracts/schemas/examples/initiative.invalid.json",
    "contracts/schemas/examples/initiative.valid.json",
    "contracts/schemas/gate-assignment.schema.json",
    "contracts/schemas/initiative-create-request.schema.json",
    "contracts/schemas/initiative-event-v1.schema.json",
    "contracts/schemas/initiative-transition-request.schema.json",
    "contracts/schemas/initiative-update-request.schema.json",
    "contracts/schemas/initiative.schema.json",
    "contracts/schemas/product.schema.json",
    "docs/curve-ai-native-sdlc-prd.md",
    "docs/technical/development-plan.md",
    "docs/technical/domain-model.md",
    "docs/technical/m0-authorization-and-state-matrices.md",
    "docs/technical/m1-01a-initiative-core-task-packet.md",
    "docs/technical/m1-alignment-evidence-prd-task-packet.md",
    "scripts/lib/context-pack.mjs",
    "scripts/lib/initiative-core.mjs",
    "scripts/tests/initiative-core.test.mjs",
    "scripts/validate-contracts.mjs",
    "scripts/validate-docs.mjs"
  ].sort(),
);

const CONTEXT_PATHS = new Map([
  ["M0-03", M0_03_CONTEXT_PATHS],
  ["M0-S3", M0_S3_CONTEXT_PATHS],
  ["M0-S4", M0_S4_CONTEXT_PATHS],
  ["M0-08", M0_08_CONTEXT_PATHS],
  ["M0-S5B", M0_08_CONTEXT_PATHS],
  ["M0-S6A", M0_S6A_CONTEXT_PATHS],
  ["RUNTIME-M0-01", RUNTIME_M0_01_CONTEXT_PATHS],
  ["M0-S9A", M0_S9A_CONTEXT_PATHS],
  ["M0-S9B", M0_S9B_CONTEXT_PATHS],
  ["M0-S9B1", M0_S9B1_CONTEXT_PATHS],
  ["M0-S9C", M0_S9C_CONTEXT_PATHS],
  ["P0-12", P0_12_CONTEXT_PATHS],
  ["P0-09", P0_09_CONTEXT_PATHS],
  ["D-002", P0_09_CONTEXT_PATHS],
  ["M1-03B", P0_09_CONTEXT_PATHS],
  ["M1-00A", M1_00A_CONTEXT_PATHS],
  ["M1-01A", M1_01A_CONTEXT_PATHS],
]);

export function contextPathsFor(taskId) {
  const paths = CONTEXT_PATHS.get(taskId);
  return paths ? [...paths] : null;
}

export function digestContextEntries(entries) {
  const ordered = [...entries].sort((left, right) => left.path.localeCompare(right.path));
  const paths = ordered.map((entry) => entry.path);
  if (new Set(paths).size !== paths.length) throw new Error("Context-pack paths must be unique.");

  const digest = createHash("sha256");
  digest.update("curve-context-pack:v1\0");
  for (const entry of ordered) {
    if (!Buffer.isBuffer(entry.contents)) throw new Error(`Context-pack entry ${entry.path} is not a Buffer.`);
    digest.update(entry.path);
    digest.update("\0");
    digest.update(String(entry.contents.length));
    digest.update("\0");
    digest.update(entry.contents);
    digest.update("\0");
  }
  return `sha256:${digest.digest("hex")}`;
}
